#!/bin/sh
MPVD_PID="$(ps aux | grep -m 1 "input-ipc-server=$XDG_RUNTIME_DIR/mpvd" | grep -v grep | awk '{print $2}')"

status() {
    if [ -n "$MPVD_PID" ]; then
        echo "mpvd is running ($MPVD_PID)"
    else
        echo 'mpvd is down'
    fi
}

log() {
    cat /tmp/mpvd.log
}

start() {
    playlist_file="$HOME"/.local/share/mpvd_playlist.m3u
    test -e "$playlist_file" ||
        touch "$playlist_file"

    if [ -z "$MPVD_PID" ]; then
        setsid -f mpv \
            --loop-playlist \
            --cache=yes \
            --cache-secs=60 \
            --demuxer-max-bytes=256MiB \
            --demuxer-readahead-secs=30 \
            --no-video \
            --idle=yes \
            --playlist="$playlist_file" \
            --input-ipc-server="$XDG_RUNTIME_DIR"/mpvd > /tmp/mpvd.log 2>&1
    fi
}

stop() {
    if [ -n "$MPVD_PID" ]; then
        kill -9 "$MPVD_PID"
    fi
}

restart() {
    stop
    MPVD_PID=""
    start
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) restart ;;
    status) status ;;
    log) log ;;
    *) echo 'Usage: mpvd start|stop|restart|status|log' ;;
esac
exit 0
